default:
  image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - setup
  - test
  - deploy

setup:
  tags:
    - docker
  stage: setup
  script:
    - npm ci
  only:
    - dev

unit_test:
  tags:
    - docker
  stage: test
  script:
    - npm run test:unit
  only:
    - dev
    
pages: 
  tags:
    - docker
  stage: deploy
  script:
    - npm run build
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up    
  only:
    - dev
    