default:
  image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - setup
  - test
  - build
  - deploy

setup:
  tags:
    - docker
  stage: setup
  script:
    - npm ci
  only:
    - dev

unit_test:
  tags:
    - docker
  stage: test
  script:
    - npm run test:unit
  only:
    - dev

build:
  tags:
    - docker
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - dev

pages:
  tags:
    - docker
  stage: deploy
  script:
    - npm run pages
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist-pages public # rename the dist-pages folder (result of npm run pages)
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - dev
